import type { NextPage } from "next";
import Head from "next/head";
import { SignIn } from "../src/components/SignIn";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Chatti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="App flex h-screen flex-col items-center justify-center font-sfpro">
        <SignIn />
      </div>
    </div>
  );
};

export default Home;
